### ISSUE TITLE
Project template does not install

### ISSUE THREAD

**Issue by ashooner** [uky-web/project_template#15]
When starting a new project template instance (e.g. in gitpod), the site-install script fails.

- Gitpod instance does not install the install_profile on start-up
- Manual execution of .ddev/uk-site-install.sh results in error:

`gzip: reference/sanitized.sql.gz: No such file or directory`

**Comment by jrul222** [comment]
Moved the gunzip command in the uk-site-install.sh script into the if statement in the dev tools package and tagged.  Composer update on project template and commited those changes to 3.0.x.

Also found another issue with install order in uky_base for uky_base_node_page so added the missing dependency and tagged that as well.
